server.port=80
server.servlet.context-path=/
spring.datasource.url=ENC(sF/ebpoSdbIhDQzska+HfRDleaDPQVl3Xxow98GCaX3+HO9yfL6EvMBfT7VXzpRkp1N3zCN1TBMvRf7YgzWCyRTMnGdcbCTm/kjViVo6g/I=)
spring.datasource.username=ENC(vw9hd8uNvE0uIPXQjREMdw==)
spring.datasource.password=ENC(8rBJmr3QfVR7cY7XXiuErftv6PmDineS)
spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jasypt.encryptor.bean=jasyptStringEncryptor
jasypt.encryptor.password=${jasypt.encryptor.password}


spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

server.tomcat.basedir=target/tomcat
spring.devtools.restart.additional-paths=src/main/java
spring.devtools.restart.exclude=static/**,public/**


# HikariCP ??
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.pool-name=your-pool-name

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.auto-commit=true

# ??? ??? ??? ?? (mybatis ?? type? ?? ?? ?? ??)
#mybatis.type-aliases-package=kr.happyjob.study.repository
# mapper.xml ?? ??
mybatis.mapper-locations=classpath:mappers/**/*.xml

# model ???? camel case ??
#mybatis.configuration.map-underscore-to-camel-case=true

fileUpload.rootPath=Z:\\FileRepository
fileUpload.virtualRootPath=/serverfile
fileUpload.userPath=user

image.allow.ext=jpg,jpeg,png,bmp

#spring.mvc.view.prefix=/WEB-INF/views/
#spring.mvc.view.suffix=.jsp

# google Login
google.request.endpoint.uri:https://accounts.google.com/o/oauth2/v2/auth
google.request.token.uri:https://oauth2.googleapis.com/token
google.request.userinfo.uri:https://www.googleapis.com/oauth2/v3/userinfo
google.redirect.uri:http://localhost/login/oauth2/process
google.query.parameter.client.id:1021558466697-kla37dmk6qbmlmborh0f3e99pugk71qr.apps.googleusercontent.com
google.query.parameter.client.secret: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
google.query.parameter.response_type:code
google.query.parameter.scope:openid profile email